var favplace = ['Makkah', 'Madinah', 'AlQuds', 'Istanbul', 'SiliconValley'];
console.log("Original Order :",favplace);
console.log("Alphabetical Order :",[...favplace].sort());
console.log("Original Order:",favplace);
console.log("Reverse_Alphabetical Order:",[...favplace].sort().reverse());
console.log("Original Order:",favplace);
console.log("Reverse Order:",[...favplace].reverse());
console.log("Original Order:",favplace);
console.log("Alphabetical Order :",[...favplace].sort());
console.log("Reverse_Alphabetical Order:",[...favplace].sort().reverse());
